# Generated by Django 3.0 on 2019-12-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome de Conta')),
                ('description', models.TextField(verbose_name='Descrição de Conta')),
                ('varcont', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da Conta')),
                ('done', models.CharField(choices=[('Pago', 'Pago'), ('Pagar', 'Pagar')], max_length=7, verbose_name='Status da Conta')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.TypeTask', verbose_name='Tipo de Conta')),
            ],
        ),
    ]
